/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.JOptionPane;
import app.User;
import java.awt.event.KeyEvent;


/**
 *
 * @author alumnogreibd
 */
public class VAutentication extends javax.swing.JDialog {

    private app.FachadaAplicacion fa;
    private int counterIntentos;
    private String idIntento;
    /**
     * Creates new form VAutenticacion
     */
        public VAutentication(java.awt.Frame parent, boolean modal, app.FachadaAplicacion fa) {
        super(parent, modal);
        BackgroundPanel panelFondo = new BackgroundPanel("/resources/background.png");
        setContentPane(panelFondo);
        initComponents();
        counterIntentos = 0;
        idIntento = "";
        this.fa = fa;
        this.lblFallo.setVisible(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(221,160,221));
    }

    private static final String ALPHA_NUMERIC_STRING = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

    public static String randomAlphaNumeric(int count) {

        StringBuilder builder = new StringBuilder();

        while (count-- != 0) {

        int character = (int)(Math.random()*ALPHA_NUMERIC_STRING.length());

        builder.append(ALPHA_NUMERIC_STRING.charAt(character));

        }

        return builder.toString();

    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogo = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogIn = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPassword = new javax.swing.JButton();
        lblFallo = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(187, 148, 206));

        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        btnLogo.setText("logo");
        btnLogo.setToolTipText("");
        btnLogo.setPreferredSize(new java.awt.Dimension(100, 100));
        btnLogo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });

        btnLogIn.setText("Iniciar Sesión");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnRegister.setText("Registrarse");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel1.setText("¿Aún no tienes cuenta?, !Regístrate!");

        btnPassword.setText("No me acuerdo de mi contraseña");
        btnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordActionPerformed(evt);
            }
        });

        lblFallo.setForeground(new java.awt.Color(255, 0, 0));
        lblFallo.setText("Usuario o contraseña incorrectos");

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUsername))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFallo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lblFallo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogIn)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnPassword)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        VRegister vr = new VRegister(fa.getFachadaGui().getVPrincipal(),true,fa);
        vr.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordActionPerformed
        // TODO add your handling code here:
        String to = JOptionPane.showInputDialog(this, "Inserte el email asociado a su cuenta:");
        String novoContrasinal = randomAlphaNumeric(8);
        String contrasinalEncriptado = app.Password.hashPasssword(novoContrasinal);
        this.fa.actualizarContrasinal(to, contrasinalEncriptado);
        this.fa.enviarEmailAplicacion(to,"Recuperación de contraseña","Su contraseña es " + novoContrasinal);
    }//GEN-LAST:event_btnPasswordActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        this.lblFallo.setVisible(false);
        User u = fa.comprobarAutentificacion(this.txtUsername.getText(),this.txtPassword.getText());
        if(u != null){
            this.fa.setUsuarioActual(u);
            this.fa.nuevoAcceso(u.getId());
            this.dispose();
            this.getParent().setVisible(true);
            ((VPrincipal)this.getParent()).actualizarLblSaldo();
            ((VPrincipal)this.getParent()).cargarFotoPerfil();
            ((VPrincipal)this.getParent()).actualizarLblNickname();
        }else{
            this.lblFallo.setVisible(true);
            if(!idIntento.equals(this.txtUsername.getText())){
                counterIntentos = 1;
                idIntento=this.txtUsername.getText();
            }
            counterIntentos++;
            if(counterIntentos>5){
                this.fa.muestraExcepcion("Número máximo de intentos de inicio de sesión superados. Saliendo de la aplicación...");
                try{
                    Thread.sleep(3000);
                }catch(InterruptedException ex){
                    System.out.println(ex.getMessage());
                }finally{
                    System.exit(0);
                }
            }
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        // TODO add your handling code here:
        this.enterKeyPressed(evt);
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:
        this.enterKeyPressed(evt);
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoActionPerformed

    private void enterKeyPressed(KeyEvent e){
        if(e.getKeyCode()==KeyEvent.VK_ENTER){
            this.lblFallo.setVisible(false);
            User u = fa.comprobarAutentificacion(this.txtUsername.getText(),this.txtPassword.getText());
            if(u != null){
                this.fa.setUsuarioActual(u);
                this.fa.nuevoAcceso(u.getId());
                this.dispose();
                this.getParent().setVisible(true);
                ((VPrincipal)this.getParent()).actualizarLblSaldo();
                ((VPrincipal)this.getParent()).cargarFotoPerfil();
                ((VPrincipal)this.getParent()).actualizarLblNickname();
            }else{
                this.lblFallo.setVisible(true);
                if(!idIntento.equals(this.txtUsername.getText())){
                    counterIntentos = 1;
                    idIntento=this.txtUsername.getText();
                }
                counterIntentos++;
                if(counterIntentos>5){
                    this.fa.muestraExcepcion("Número máximo de intentos de inicio de sesión superados. Saliendo de la aplicación...");
                    try{
                        Thread.sleep(3000);
                    }catch(InterruptedException ex){
                        System.out.println(ex.getMessage());
                    }finally{
                        System.exit(0);
                    }
                }
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnLogo;
    private javax.swing.JButton btnPassword;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFallo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
