/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author alumnogreibd
 */
public class VPendingParties extends javax.swing.JDialog {

    /**
     * Creates new form VPendingParties
     */
    app.FachadaAplicacion fa;
    public VPendingParties(java.awt.Frame parent, boolean modal,app.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa=fa;
        BackgroundPanel panelFondo = new BackgroundPanel("/resources/background.png");
        setContentPane(panelFondo);
        initComponents();
        this.setLocationRelativeTo(null);
        PendingPartiesTableModel mFest = new PendingPartiesTableModel();
        this.tablaFestas.setModel(mFest);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFestas = new javax.swing.JTable();
        btnVer = new javax.swing.JButton();
        btnDeixarFesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "todas", "organizador", "participante" }));

        jLabel2.setText("Tipo");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaFestas.setModel(new PendingPartiesTableModel());
        jScrollPane1.setViewportView(tablaFestas);

        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btnDeixarFesta.setText("Deixar Festa");
        btnDeixarFesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeixarFestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnVer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeixarFesta)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVer)
                    .addComponent(btnDeixarFesta))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeixarFestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeixarFestaActionPerformed
        // TODO add your handling code here:
        PendingPartiesTableModel mFP;
        mFP = (PendingPartiesTableModel) tablaFestas.getModel();
        app.Party festa=mFP.obtenerFesta(tablaFestas.getSelectedRow());
        if(festa.getHost().equals(this.fa.getUsuarioActual().getId())){
            this.fa.muestraExcepcion("O usuario e o organizador da festa, para abandonala debe borrala");
        }
        else{
            int eleccion=JOptionPane.showConfirmDialog(rootPane, "Seguro que desexa deixar a festa seleccionada?");
            if(eleccion==0){ 
                this.fa.deixarFesta(festa.getId(),this.fa.getUsuarioActual().getId());
                this.fa.muestraExcepcion("Se ha cancelado tu asistencia a la fiesta correctamente");
            }
        }
    }//GEN-LAST:event_btnDeixarFestaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        PendingPartiesTableModel mFest=(PendingPartiesTableModel)this.tablaFestas.getModel();
        
        java.util.List festas=null;
        switch((String)this.cbTipo.getSelectedItem()){
            case "participante":
                festas=this.fa.buscarFPparticipante(this.fa.getUsuarioActual().getId(),this.txtNome.getText());
                break;
            case "organizador":
                festas=this.fa.buscarFPorganizador(this.fa.getUsuarioActual().getId(),this.txtNome.getText());
                break;
            default:
                festas=this.fa.buscarFPorganizador(this.fa.getUsuarioActual().getId(),this.txtNome.getText());
                festas.addAll(this.fa.buscarFPparticipante(this.fa.getUsuarioActual().getId(),this.txtNome.getText()));
        }
        mFest.setFilas(festas);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        PendingPartiesTableModel mFP;
         mFP = (PendingPartiesTableModel) tablaFestas.getModel();
        boolean organizador=false;
        app.Party festa=mFP.obtenerFesta(tablaFestas.getSelectedRow());
        if(this.fa.consultarOrganizador(festa.getId()).equals(this.fa.getUsuarioActual().getId())){
                    organizador=true;
                }
                VParty vf=new VParty(this.fa.getFachadaGui().getVPrincipal(), true,this.fa, festa.getId(),this.fa.consultarPosts(festa.getId()),organizador,"hola");
                vf.setVisible(true);
    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDeixarFesta;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFestas;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
