/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.Image;
import javax.imageio.ImageIO;

/**
 *
 * @author alumnogreibd
 */
public class VPrincipal extends javax.swing.JFrame {

    private app.FachadaAplicacion fa;
    
    /**
     * Creates new form VPrincipal
     */
    public VPrincipal(app.FachadaAplicacion fa) {
        BackgroundPanel panelFondo = new BackgroundPanel("/resources/background.png");
        setContentPane(panelFondo);
        initComponents();
        this.fa = fa;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(221,160,221));
        this.setVisible(false);
        this.btnOrganizarFiesta.setEnabled(false);
        this.btnFiestasPasadas.setEnabled(false);
        //this.actualizarLblSaldo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fotoPerfil = new javax.swing.JToggleButton();
        lblNickname = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnBuscarFiestas = new javax.swing.JButton();
        btnFiestasPendientes = new javax.swing.JButton();
        btnFiestasPasadas = new javax.swing.JButton();
        btnAmigos = new javax.swing.JButton();
        btnOrganizarFiesta = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblSaldoDisponible = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        btnSaldo = new javax.swing.JButton();
        btnSaldo2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fotoPerfil.setContentAreaFilled(false);
        fotoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoPerfilActionPerformed(evt);
            }
        });

        lblNickname.setText("N I C K N A M E");

        btnEditarPerfil.setText("Editar Perfil");
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Invitaciones Pendientes:");

        jButton2.setText("f");

        jButton3.setText("f");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("f");

        jButton5.setText("f");

        jButton6.setText("f");

        btnBuscarFiestas.setText("BUSCAR FIESTA");
        btnBuscarFiestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFiestasActionPerformed(evt);
            }
        });

        btnFiestasPendientes.setText("FESTAS PENDENTES");
        btnFiestasPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiestasPendientesActionPerformed(evt);
            }
        });

        btnFiestasPasadas.setText("FESTAS PASADAS");

        btnAmigos.setText("AMIGOS");
        btnAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmigosActionPerformed(evt);
            }
        });

        btnOrganizarFiesta.setText("ORGANIZAR FESTA");
        btnOrganizarFiesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizarFiestaActionPerformed(evt);
            }
        });

        btnSalir.setText("Sair");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblSaldoDisponible.setText("Saldo Disponible:");

        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setText("0.00€");

        btnSaldo.setText("Recargar saldo");
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });

        btnSaldo2.setText("Retirar saldo");
        btnSaldo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarFiestas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFiestasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFiestasPasadas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOrganizarFiesta, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEditarPerfil)
                                    .addComponent(lblNickname))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSaldoDisponible)
                                .addGap(37, 37, 37)
                                .addComponent(lblSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(227, 227, 227)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(btnSaldo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSaldoDisponible)
                            .addComponent(lblSaldo)
                            .addComponent(btnSaldo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnSaldo2))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblNickname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarPerfil)
                            .addComponent(btnBuscarFiestas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFiestasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOrganizarFiesta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFiestasPasadas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void fotoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fotoPerfilActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.fa.acabarAcceso(this.fa.getUsuarioActual().getId());
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBuscarFiestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFiestasActionPerformed
        // TODO add your handling code here:
        VSearchParty vf=new VSearchParty(this,true, this.fa);
        vf.setVisible(true);
   
    }//GEN-LAST:event_btnBuscarFiestasActionPerformed

    public void actualizarLblSaldo(){
        this.lblSaldo.setText(this.fa.consultarSaldo(this.fa.getUsuarioActual().getId()) + "€");
    }
    
    public void actualizarLblNickname(){
        this.lblNickname.setText(this.fa.getUsuarioActual().getId().toUpperCase());
    }
    
    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false); //Si esta linea esta activa, al salir de editar perfil perdemos la app
        VProfile vp = new VProfile(this,true,fa);
        vp.setVisible(true);
    }//GEN-LAST:event_btnEditarPerfilActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        String to = JOptionPane.showInputDialog(this, "Inserte la cantidad que desee recargar en su cuenta:");
        float saldo = 0;
        try{
            saldo = Float.parseFloat(to);
        }catch(Exception e){
            this.fa.muestraExcepcion("No se ha podido recargar la cantidad indicada");
            return;
        }
        if(saldo < 0){
            this.fa.muestraExcepcion("El saldo a recargar debe ser una cantidad positiva");
            return;
        }
        this.fa.recargarSaldo(saldo);
        String message = "Se han recargado " + saldo + "€ en su cuenta. "
                + "Su saldo actual es de " + this.fa.consultarSaldo(this.fa.getUsuarioActual().getId()) + "€";
        this.fa.enviarEmailAplicacion(this.fa.getUsuarioActual().getEmail(),"Recarga de saldo", message);
        this.fa.muestraExcepcion("Recarga realizada correctamente. Puede comprobarlo en su correo");
        //TODO meter jpane que notifique update sin ser muestra excpecion
        this.actualizarLblSaldo();
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnFiestasPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiestasPendientesActionPerformed
        // TODO add your handling code here:
        VPendingParties vfp=new VPendingParties(this,true,this.fa);
        vfp.setVisible(true);
    }//GEN-LAST:event_btnFiestasPendientesActionPerformed

    private void btnOrganizarFiestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizarFiestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrganizarFiestaActionPerformed

    private void btnAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmigosActionPerformed
        // TODO add your handling code here:
        VUserSearch vb = new VUserSearch((java.awt.Frame) this.getParent(), true, this.fa, this.fa.getUsuarioActual().getId(), this);
        vb.setVisible(true);
    }//GEN-LAST:event_btnAmigosActionPerformed

    private void btnSaldo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldo2ActionPerformed
        // TODO add your handling code here:
        String to = JOptionPane.showInputDialog(this, "Inserte la cantidad que desee retirar de su cuenta:");
        float saldo = 0;
        try{
            saldo = Float.parseFloat(to);
        }catch(Exception e){
            this.fa.muestraExcepcion("No se ha podido retirar la cantidad indicada");
            return;
        }
        if(saldo - this.fa.consultarSaldo(this.fa.getUsuarioActual().getId())< 0){
            this.fa.recargarSaldo((-1) * saldo);
            String message = "Se han retirado " + saldo + "€ de su cuenta/n"
                    + "Su saldo actual es de " + this.fa.consultarSaldo(this.fa.getUsuarioActual().getId()) + "€";
            this.fa.enviarEmailAplicacion(this.fa.getUsuarioActual().getEmail(), "Retirada de saldo", message);
            this.fa.muestraExcepcion("Retirada realizada correctamente. Puede comprobarlo en su correo");
            //TODO meter jpane que notifique update sin ser muestra excpecion
            this.actualizarLblSaldo();
        }
        else this.fa.muestraExcepcion("No tiene saldo suficiente para retirar esa cantidad");
        
    }//GEN-LAST:event_btnSaldo2ActionPerformed

    public void cargarFotoPerfil(){
        try{
            Image img = ImageIO.read(getClass().getResource(this.fa.getUsuarioActual().getUrlFotoPerfil()));
            this.fotoPerfil.setIcon(new javax.swing.ImageIcon(img));
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmigos;
    private javax.swing.JButton btnBuscarFiestas;
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JButton btnFiestasPasadas;
    private javax.swing.JButton btnFiestasPendientes;
    private javax.swing.JButton btnOrganizarFiesta;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnSaldo2;
    private javax.swing.JButton btnSalir;
    private javax.swing.JToggleButton fotoPerfil;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldoDisponible;
    // End of variables declaration//GEN-END:variables
}
