/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import app.Company;
import app.Particular;
import app.User;
import javax.swing.JOptionPane;
import app.SocialNetwork;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author alumnogreibd
 */
public class VProfile extends javax.swing.JDialog {

    private app.FachadaAplicacion fa;
    private UtilDateModel model;
    private JDatePanelImpl datePanel;
    private JDatePickerImpl datePicker;
    private User usuario;
    
    
    /**
     * Creates new form VPerfil
     */
    public VProfile(java.awt.Frame parent, boolean modal, app.FachadaAplicacion fa) {
        super(parent, modal);
        BackgroundPanel panelFondo = new BackgroundPanel("/resources/background.png");
        setContentPane(panelFondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.fa = fa;
        this.getContentPane().setBackground(new Color(221,160,221));
        Properties p = new Properties();
        p.put("text.day","Day");
        p.put("text.month","Month");
        p.put("text.year","Year");
        this.model = new UtilDateModel();
        this.datePanel = new JDatePanelImpl(this.model,p);
        this.datePicker = new JDatePickerImpl(datePanel, new DashDateLabelFormatter());
        datePicker.setBounds(160,200,200,20);
        this.cargarUsuarioActual(this.fa.getUsuarioActual());
        this.cargarFotoPerfil();
    }

    public User getUsuario(){
        return this.usuario;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exploradorArchivos = new javax.swing.JFileChooser();
        btnCambiarContrasinal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblNacimiento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        txtNacimiento = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        btnCambiarFoto = new javax.swing.JButton();
        txtGenero = new javax.swing.JTextField();
        btnFotoPerfil = new javax.swing.JButton();
        lblNickname = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblBiografia = new javax.swing.JLabel();
        txtBiografia = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnInstagram = new javax.swing.JButton();
        btnTwitter = new javax.swing.JButton();
        btnFacebook = new javax.swing.JButton();
        btnGitHub = new javax.swing.JButton();
        btnLinkedin = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnEditarRedes = new javax.swing.JButton();
        btnDarseBaja = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCambiarContrasinal.setText("Cambiar Contraseña");
        btnCambiarContrasinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContrasinalActionPerformed(evt);
            }
        });

        jLabel9.setText("Historial de fiestas");

        lblNacimiento.setText("Nacimiento");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        lblGenero.setText("Género");

        btnCambiarFoto.setText("Cambiar foto");
        btnCambiarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarFotoActionPerformed(evt);
            }
        });

        txtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroActionPerformed(evt);
            }
        });

        btnFotoPerfil.setContentAreaFilled(false);

        lblNickname.setText("Nombre de Usuario");

        lblCorreo.setText("Correo Electrónico");

        jLabel10.setText("También estoy en...");

        lblNome.setText("Nombre");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblBiografia.setText("Biografia");

        txtBiografia.setText("jTextField7");
        txtBiografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiografiaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnInstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/instalogo.jpeg"))); // NOI18N
        btnInstagram.setContentAreaFilled(false);
        btnInstagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstagramActionPerformed(evt);
            }
        });

        btnTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/twitterLogo.png"))); // NOI18N
        btnTwitter.setContentAreaFilled(false);
        btnTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwitterActionPerformed(evt);
            }
        });

        btnFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/facebookLogo.png"))); // NOI18N
        btnFacebook.setContentAreaFilled(false);
        btnFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacebookActionPerformed(evt);
            }
        });

        btnGitHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/githubLogo.png"))); // NOI18N
        btnGitHub.setContentAreaFilled(false);
        btnGitHub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGitHubActionPerformed(evt);
            }
        });

        btnLinkedin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/linkedinlogo.jpeg"))); // NOI18N
        btnLinkedin.setContentAreaFilled(false);
        btnLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinkedinActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tinder.jpeg"))); // NOI18N
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btnEditarRedes.setText("Editar Redes");
        btnEditarRedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRedesActionPerformed(evt);
            }
        });

        btnDarseBaja.setText("Darse de baja de la aplicación");
        btnDarseBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarseBajaActionPerformed(evt);
            }
        });

        lblEstado.setText("Estado Sentimental");

        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backArrow.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblNome)
                                                .addComponent(lblCorreo)
                                                .addComponent(txtCorreo)
                                                .addComponent(txtBiografia, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                                .addComponent(jLabel10)
                                                .addComponent(txtNome)
                                                .addComponent(txtEstado))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnCambiarContrasinal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(11, 11, 11)
                                                        .addComponent(btnInstagram)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(btnTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(btnLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(btnGitHub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEditarRedes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnDarseBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblEstado)
                                    .addComponent(lblBiografia)
                                    .addComponent(lblGenero)
                                    .addComponent(lblNacimiento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGenero)
                                .addGap(331, 331, 331))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnFotoPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCambiarFoto)
                                .addGap(57, 57, 57))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCorreo)
                        .addGap(12, 12, 12)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(lblEstado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnCambiarFoto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblBiografia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBiografia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInstagram, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTwitter)
                                    .addComponent(btnLinkedin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFacebook)
                                    .addComponent(btnGitHub)
                                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEditarRedes)
                                .addGap(36, 36, 36)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCambiarContrasinal)
                            .addComponent(btnGuardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(btnDarseBaja))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroActionPerformed

    private void txtBiografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiografiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiografiaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    String nome=this.txtNome.getText();
    String correo=this.txtCorreo.getText();   
    String biografia=this.txtBiografia.getText();
    String xenero=this.txtGenero.getText();//Empresas->CIF
    String estado=this.txtEstado.getText();//Empresas->Direccion
    String nacimiento=this.txtNacimiento.getText();//Empresas->Web
    if(this.usuario instanceof Particular){
        String date = datePicker.getJFormattedTextField().getText();
        if(date == null){
            this.fa.muestraExcepcion("Introduzca una fecha de nacimiento válida");
            return;
        }
        System.out.println(xenero);
        Particular p=new Particular(this.usuario,date,estado,xenero);
        p.setNome(nome);
        p.setEmail(correo);
        p.setBiografia(biografia);
        this.fa.editarPerfil(p);
    }
    else{
        Company emp=new Company(this.usuario,xenero,estado,nacimiento);
        emp.setNome(nome);
        emp.setEmail(correo);
        emp.setBiografia(biografia);
        this.fa.editarPerfil(emp);
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCambiarContrasinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContrasinalActionPerformed
        // TODO add your handling code here:
        VChangePassword vp = new VChangePassword(this.fa.getFachadaGui().getVPrincipal(),true,fa,usuario);
        vp.setVisible(true);
    }//GEN-LAST:event_btnCambiarContrasinalActionPerformed

    private void btnEditarRedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRedesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        VSocialNetworks vr = new VSocialNetworks((javax.swing.JFrame) this.getParent(),true,fa,this,this.fa.consultarRedes(this.usuario.getId()));
        vr.setVisible(true);
    }//GEN-LAST:event_btnEditarRedesActionPerformed

    private void btnInstagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstagramActionPerformed
        // TODO add your handling code here:
        SocialNetwork red = this.fa.consultarRedSocial(usuario.getId(),"instagram");
        if(red != null){
            String mensaje = "ID: " + red.getId_plataforma() + "\nURL: " + red.getUrl();
            JOptionPane.showMessageDialog(null,mensaje );
        }else{
            JOptionPane.showMessageDialog(null,"El usuario no está presente en esta red social");
        }
    }//GEN-LAST:event_btnInstagramActionPerformed

    private void btnTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwitterActionPerformed
        // TODO add your handling code here:
        SocialNetwork red = this.fa.consultarRedSocial(usuario.getId(),"twitter");
        if(red != null){
            String mensaje = "ID: " + red.getId_plataforma() + "\nURL: " + red.getUrl();
            JOptionPane.showMessageDialog(null,mensaje );
        }else{
            JOptionPane.showMessageDialog(null,"El usuario no está presente en esta red social");
        }
    }//GEN-LAST:event_btnTwitterActionPerformed

    private void btnLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinkedinActionPerformed
        // TODO add your handling code here:
        SocialNetwork red = this.fa.consultarRedSocial(usuario.getId(),"linkedin");
        if(red != null){
            String mensaje = "ID: " + red.getId_plataforma() + "\nURL: " + red.getUrl();
            JOptionPane.showMessageDialog(null,mensaje );
        }else{
            JOptionPane.showMessageDialog(null,"El usuario no está presente en esta red social");
        }
    }//GEN-LAST:event_btnLinkedinActionPerformed

    private void btnGitHubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGitHubActionPerformed
        // TODO add your handling code here:
        SocialNetwork red = this.fa.consultarRedSocial(usuario.getId(),"github");
        if(red != null){
            String mensaje = "ID: " + red.getId_plataforma() + "\nURL: " + red.getUrl();
            JOptionPane.showMessageDialog(null,mensaje );
        }else{
            JOptionPane.showMessageDialog(null,"El usuario no está presente en esta red social");
        }
    }//GEN-LAST:event_btnGitHubActionPerformed

    private void btnFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacebookActionPerformed
        // TODO add your handling code here:
        SocialNetwork red = this.fa.consultarRedSocial(usuario.getId(),"facebook");
        if(red != null){
            String mensaje = "ID: " + red.getId_plataforma() + "\nURL: " + red.getUrl();
            JOptionPane.showMessageDialog(null,mensaje );
        }else{
            JOptionPane.showMessageDialog(null,"El usuario no está presente en esta red social");
        }
    }//GEN-LAST:event_btnFacebookActionPerformed

    private void btnDarseBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarseBajaActionPerformed
        // TODO add your handling code here:
        String contrasinal = JOptionPane.showInputDialog("Introduzca su contraseña para confirmar la acción");
        if(app.Password.checkPassword(contrasinal,this.fa.recuperarContrasinal(this.usuario.getEmail()))){          
            float cantidad = this.fa.darBajaUsuario(usuario.getId());
            if(cantidad < 0){
                this.fa.muestraExcepcion("No puedes darte de baja si eres el organizador de una fiesta");
                return;
            }
            VWarning va = new VWarning((javax.swing.JFrame) this.getParent(),true,"Se ha dado de baja con " + cantidad + "€ de saldo que se le serán reembolsados");
            va.setVisible(true);
            try{
                Thread.sleep(5000);
            }catch(InterruptedException ex){
                System.out.println(ex.getMessage());
            }finally{
                this.fa.muestraExcepcion("Esperamos volver a verle pronto");
                try{
                    Thread.sleep(2000);
                }catch(InterruptedException ex){
                    System.out.println(ex.getMessage());
                }finally{
                    System.exit(0);
                }
            }
                
            //TODO engadir metodos dar de baixa
        }else{
            JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta");
        }
    }//GEN-LAST:event_btnDarseBajaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        SocialNetwork red = this.fa.consultarRedSocial(usuario.getId(),"tinder");
        if(red != null){
            String mensaje = "ID: " + red.getId_plataforma() + "\nURL: " + red.getUrl();
            JOptionPane.showMessageDialog(null,mensaje );
        }else{
            JOptionPane.showMessageDialog(null,"El usuario no está presente en esta red social");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // 
        //VFesta vf = new VFesta((java.awt.Frame)this.getParent(), true, fa, 1, this, fa.consultarPosts(1),this.fa.consultarOrganizador(this.usuario.getId()));
        //vf.setVisible(true);
    }//GEN-LAST:event_formMouseClicked


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //VFesta vf = new VFesta((javax.swing.JFrame) this.getParent(),true, this.fa,1,this,fa.consultarPosts(1),this.fa.consultarOrganizador(this.usuario.getId()));
        //vf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void btnCambiarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarFotoActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        this.exploradorArchivos.showOpenDialog(this);
        File archivo=exploradorArchivos.getSelectedFile();
        String urlPerfil=null;
        //Verificamos a seleccion dun arquivo
        if(archivo!=null){
            try{
                //Definimos el destino del archivo, que sera la carpeta /Multimedia/
                String Dest= "/resources/"+archivo.getName();
                Path Destino= Paths.get(Dest);
                //Definimos el origen, que sera el archivo seleccionado
                String Orig= archivo.getPath();
                Path Origen= Paths.get(Orig);
                ///Copiamos el nuevo archivo con la clase Files, reemplazamos si ya existe uno igual
                //Files.copy(Origen,Destino,REPLACE_EXISTING);//Mover de sitio
                
                if (new EvaluaExtension().accept(archivo, ".jpeg")||new EvaluaExtension().accept(archivo, ".jpg")||new EvaluaExtension().accept(archivo, ".png")) {
                    urlPerfil = Dest;
                    this.fa.actualizarFotoPerfil(urlPerfil,usuario.getId());
                }else{
                    this.fa.muestraExcepcion("La extensión seleccionada es incorrecta");
                }
                
                try{
                    Image img = ImageIO.read(getClass().getResource(urlPerfil));
                    btnFotoPerfil.setIcon(new javax.swing.ImageIcon(img));
                }catch(Exception ex){
                    System.out.println(ex.getMessage());
                }
              
            } catch (Exception ex) {
                Logger.getLogger(VGallery.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnCambiarFotoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    
    
    private void cargarUsuarioActual(User u){
        this.lblNickname.setText(u.getId());
        this.txtNome.setText(u.getNome());
        this.txtCorreo.setText(u.getEmail());
        this.txtBiografia.setText(u.getBiografia());
        usuario=u;
        
        if(usuario instanceof Particular){
            Particular p=(Particular)u;
            this.txtGenero.setText(p.getGenero());
            this.txtEstado.setText(p.getEstadoSentimental());
            this.txtNacimiento.setVisible(false);
            this.add(datePicker);
            this.datePicker.getJFormattedTextField().setText(p.getFechaNacimiento());
        }
        else{
            Company emp=(Company)u;
            this.lblGenero.setText("CIF");
            this.txtGenero.setText(emp.getCif());
            this.lblEstado.setText("Direccion");
            this.txtEstado.setText(emp.getDireccion());
            this.lblNacimiento.setText("Pagina web");
            this.txtNacimiento.setText(emp.getWeb());            
        }
    }
    
    public void cargarFotoPerfil(){
        try{
            Image img = ImageIO.read(getClass().getResource(this.fa.getUsuarioActual().getUrlFotoPerfil()));
            this.btnFotoPerfil.setIcon(new javax.swing.ImageIcon(img));
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCambiarContrasinal;
    private javax.swing.JButton btnCambiarFoto;
    private javax.swing.JButton btnDarseBaja;
    private javax.swing.JButton btnEditarRedes;
    private javax.swing.JButton btnFacebook;
    private javax.swing.JButton btnFotoPerfil;
    private javax.swing.JButton btnGitHub;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInstagram;
    private javax.swing.JButton btnLinkedin;
    private javax.swing.JButton btnTwitter;
    private javax.swing.JFileChooser exploradorArchivos;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBiografia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNacimiento;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtBiografia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNacimiento;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
