/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import app.User;
import app.Particular;
import java.util.Properties;
import app.Company;
import java.awt.Color;
import java.io.*;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Image;
import javax.imageio.ImageIO;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author alumnogreibd
 */
public class VRegister extends javax.swing.JDialog {

    private app.FachadaAplicacion fa;   

    private UtilDateModel model;
    private JDatePanelImpl datePanel;
    private JDatePickerImpl datePicker;
    String urlPerfil;
    
    /**
     * Creates new form JRegistro
     */
    public VRegister(java.awt.Frame parent, boolean modal, app.FachadaAplicacion fa) {
        super(parent, modal);
        BackgroundPanel panelFondo = new BackgroundPanel("/resources/background.png");
        setContentPane(panelFondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.fa = fa;
        this.lblFalloEmail.setVisible(false);
        this.lblFalloId.setVisible(false);
        this.lblFalloPassword.setVisible(false);
        this.lblFalloEmailEmpresa.setVisible(false);
        this.lblFalloIdEmpresa.setVisible(false);
        this.lblFalloFecha.setVisible(false);
        this.lblFalloPasswordEmpresa.setVisible(false);
        this.getContentPane().setBackground(new Color(221,160,221));
        this.jPanel1.setBackground(new Color(221,160,221));
        this.jPanel2.setBackground(new Color(221,160,221));
        setContentPane(panelFondo);
        Properties p = new Properties();
        p.put("text.day","Day");
        p.put("text.month","Month");
        p.put("text.year","Year");
        this.model = new UtilDateModel();
        this.datePanel = new JDatePanelImpl(this.model,p);
        this.datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());
        datePicker.setBounds(530,310,200,20);
        this.jPanel1.add(datePicker);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exploradorArchivos = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblFalloIdEmpresa = new javax.swing.JLabel();
        lblNickname1 = new javax.swing.JLabel();
        txtIdEmpresa = new javax.swing.JTextField();
        lblNome1 = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        lblFalloEmailEmpresa = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        txtEmailEmpresa = new javax.swing.JTextField();
        lblFalloPasswordEmpresa = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblConfirmarClave1 = new javax.swing.JLabel();
        txtPasswordEmpresa = new javax.swing.JPasswordField();
        txtConfirmPasswordEmpresa = new javax.swing.JPasswordField();
        btnRegisterEmpresa = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        txtBiografiaEmpresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblFoto1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCif = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblWeb = new javax.swing.JLabel();
        txtWeb = new javax.swing.JTextField();
        fotoPerfil = new javax.swing.JToggleButton();
        btnSubir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNickname = new javax.swing.JLabel();
        lblFalloPassword = new javax.swing.JLabel();
        lblConfirmarClave = new javax.swing.JLabel();
        lblFalloEmail = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblFalloId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtBiografia = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnGenero = new javax.swing.JComboBox();
        btnSoltero = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        lblFalloFecha = new javax.swing.JLabel();
        btnSubir1 = new javax.swing.JButton();
        fotoPerfil1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO DE REGISTRO");

        lblFalloIdEmpresa.setForeground(new java.awt.Color(251, 4, 4));
        lblFalloIdEmpresa.setText("Ese nickname ya está siendo usado");

        lblNickname1.setText("Nickname");

        lblNome1.setText("Nome");

        lblFalloEmailEmpresa.setForeground(new java.awt.Color(255, 0, 0));
        lblFalloEmailEmpresa.setText("Por favor, introduzca un email válido");

        lblEmail1.setText("Email");

        lblFalloPasswordEmpresa.setForeground(new java.awt.Color(255, 0, 0));
        lblFalloPasswordEmpresa.setText("Las contraseñas introducidas no coinciden");

        jLabel7.setText("Clave");

        lblConfirmarClave1.setText("Confirmar clave:");

        btnRegisterEmpresa.setText("Registrarse");
        btnRegisterEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterEmpresaActionPerformed(evt);
            }
        });

        btnSalir1.setText("Salir");

        jLabel5.setText("Biografia");

        lblFoto1.setText("Foto Perfil:");

        jLabel8.setText("CIF");

        lblDireccion.setText("Dirección");

        lblWeb.setText("Web");

        fotoPerfil.setContentAreaFilled(false);
        fotoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoPerfilActionPerformed(evt);
            }
        });

        btnSubir.setText("Subir archivo");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSubir)
                                    .addComponent(lblFoto1))
                                .addGap(130, 130, 130)
                                .addComponent(fotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtBiografiaEmpresa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDireccion)
                                        .addComponent(lblWeb))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCif, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addComponent(btnRegisterEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(185, 185, 185))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFalloIdEmpresa)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblEmail1)
                                    .addGap(86, 86, 86)
                                    .addComponent(txtEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblFalloPasswordEmpresa)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblConfirmarClave1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPasswordEmpresa))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(87, 87, 87)
                                        .addComponent(txtConfirmPasswordEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblFalloEmailEmpresa, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblNickname1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(lblNome1))
                            .addGap(314, 582, Short.MAX_VALUE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFoto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubir)
                        .addGap(22, 22, 22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtBiografiaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeb)
                    .addComponent(txtWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(lblFalloIdEmpresa)
                    .addGap(26, 26, 26)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNickname1)
                        .addComponent(txtIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNome1)
                        .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(lblFalloEmailEmpresa)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail1)
                        .addComponent(txtEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(9, 9, 9)
                    .addComponent(lblFalloPasswordEmpresa)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtConfirmPasswordEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConfirmarClave1)
                        .addComponent(txtPasswordEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addComponent(btnRegisterEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(20, 20, 20)))
        );

        jTabbedPane1.addTab("Empresa", jPanel2);

        lblNickname.setText("Nickname");

        lblFalloPassword.setForeground(new java.awt.Color(255, 0, 0));
        lblFalloPassword.setText("Las contraseñas introducidas no coinciden");

        lblConfirmarClave.setText("Confirmar clave:");

        lblFalloEmail.setForeground(new java.awt.Color(255, 0, 0));
        lblFalloEmail.setText("Por favor, introduzca un email válido");

        lblFalloId.setForeground(new java.awt.Color(251, 4, 4));
        lblFalloId.setText("Ese nickname ya está siendo usado");

        jLabel4.setText("Biografia");

        lblNome.setText("Nome");

        jLabel6.setText("Clave");

        btnRegister.setText("Registrarse");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblEmail.setText("Email");

        btnSalir.setText("Salir");

        lblFoto.setText("Foto Perfil:");

        jLabel2.setText("lblGenero");

        btnGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer", "Otro" }));

        btnSoltero.setText("Estoy Soltero/a");

        jLabel3.setText("Fecha Nacimiento");

        lblFalloFecha.setForeground(new java.awt.Color(254, 9, 36));
        lblFalloFecha.setText("Por favor, seleccione una fecha");

        btnSubir1.setText("Subir archivo");
        btnSubir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubir1ActionPerformed(evt);
            }
        });

        fotoPerfil1.setContentAreaFilled(false);
        fotoPerfil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoPerfil1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFalloId)
                            .addComponent(lblFalloPassword)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblConfirmarClave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblNome)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblEmail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNickname)
                                        .addGap(51, 51, 51)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFalloEmail))))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblFalloFecha)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblFoto)
                                            .addGap(38, 38, 38)
                                            .addComponent(btnSubir1))
                                        .addComponent(jLabel4))
                                    .addGap(30, 30, 30)
                                    .addComponent(fotoPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSoltero))
                                    .addComponent(txtBiografia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFalloId)
                            .addComponent(lblFoto)
                            .addComponent(btnSubir1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNickname)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(fotoPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBiografia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFalloEmail))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSoltero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(lblFalloPassword)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFalloFecha)
                    .addComponent(jLabel6)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmarClave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Particular", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterEmpresaActionPerformed
        // TODO add your handling code here:
        this.lblFalloEmailEmpresa.setVisible(false);
        this.lblFalloPasswordEmpresa.setVisible(false);
        this.lblFalloIdEmpresa.setVisible(true);
        if(!this.txtEmailEmpresa.getText().contains("@")){
            this.lblFalloEmailEmpresa.setVisible(true);
            return;
        }
        if(!this.txtPasswordEmpresa.getText().equals(this.txtConfirmPasswordEmpresa.getText())){
            this.lblFalloPasswordEmpresa.setVisible(true);
            return;
        }
        
        if(this.urlPerfil == null){
            this.urlPerfil = "/resources/p.jpeg";
        }
        
        Company e = new Company(this.txtIdEmpresa.getText(),app.Password.hashPasssword(this.txtPasswordEmpresa.getText()),this.txtNomeEmpresa.getText(),this.txtEmailEmpresa.getText(),(float)0,this.txtBiografiaEmpresa.getText(),this.urlPerfil,this.txtCif.getText(),this.txtDireccion.getText(),this.txtWeb.getText());
        
        if(!this.fa.darAltaUsuario(e)){
            this.lblFalloIdEmpresa.setVisible(true);
        }else{
            this.fa.setUsuarioActual(e);
            this.fa.nuevoAcceso(e.getId());
            this.dispose();
            this.getParent().setVisible(true);
            ((VPrincipal)this.getParent()).cargarFotoPerfil();
            ((VPrincipal)this.getParent()).actualizarLblNickname();
        }
    }//GEN-LAST:event_btnRegisterEmpresaActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        this.lblFalloEmail.setVisible(false);
        this.lblFalloPassword.setVisible(false);
        this.lblFalloId.setVisible(true);
        if(!this.txtEmail.getText().contains("@")){
            this.lblFalloEmail.setVisible(true);
            return;
        }
        if(!this.txtPassword.getText().equals(this.txtConfirmPassword.getText())){
            this.lblFalloPassword.setVisible(true);
            return;
        }
        String date = datePicker.getJFormattedTextField().getText();
        if(date == null){
            this.lblFalloFecha.setVisible(true);
            return;
        }
        
        if(this.urlPerfil == null){
            this.urlPerfil = "/resources/p.jpeg";
        }
        
        String soltero = this.btnSoltero.isSelected() ? "Soltero" : "Con pareja";
        
        Particular u = new Particular(this.txtId.getText(),app.Password.hashPasssword(this.txtPassword.getText()),this.txtNome.getText(),this.txtEmail.getText(),(float)0,this.txtBiografia.getText(),this.urlPerfil,date,soltero,this.btnGenero.getSelectedItem().toString());
        
        if(!this.fa.darAltaUsuario(u)){
            this.lblFalloId.setVisible(true);
        }else{
            this.fa.setUsuarioActual(u);
            this.fa.nuevoAcceso(u.getId());
            this.dispose();
            this.getParent().setVisible(true);
            ((VPrincipal)this.getParent()).cargarFotoPerfil();
            ((VPrincipal)this.getParent()).actualizarLblNickname();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void fotoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fotoPerfilActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // TODO add your handling code here:
        this.exploradorArchivos.showOpenDialog(this);
        File archivo=exploradorArchivos.getSelectedFile();
        //Verificamos a seleccion dun arquivo
        if(archivo!=null){
            try{
                //Definimos el destino del archivo, que sera la carpeta /Multimedia/
                String Dest= "/resources/"+archivo.getName();
                Path Destino= Paths.get(Dest);
                //Definimos el origen, que sera el archivo seleccionado
                String Orig= archivo.getPath();
                Path Origen= Paths.get(Orig);
                ///Copiamos el nuevo archivo con la clase Files, reemplazamos si ya existe uno igual
                //Files.copy(Origen,Destino,REPLACE_EXISTING);//Mover de sitio
                
                if (new EvaluaExtension().accept(archivo, ".jpeg")||new EvaluaExtension().accept(archivo, ".jpg")||new EvaluaExtension().accept(archivo, ".png")) {
                    this.urlPerfil = Dest;
                    System.out.println(urlPerfil);
                }else{
                    this.fa.muestraExcepcion("La extensión seleccionada es incorrecta");
                }
                
                try{
                    Image img = ImageIO.read(getClass().getResource(this.urlPerfil));
                    this.fotoPerfil.setIcon(new javax.swing.ImageIcon(img));
                }catch(Exception ex){
                    System.out.println(ex.getMessage());
                }
              
            } catch (Exception ex) {
                Logger.getLogger(VGallery.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        //Falta cerrar el exploradorDeArchivos
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnSubir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubir1ActionPerformed
        // TODO add your handling code here:
        this.exploradorArchivos.showOpenDialog(this);
        File archivo=exploradorArchivos.getSelectedFile();
        //Verificamos a seleccion dun arquivo
        if(archivo!=null){
            try{
                //Definimos el destino del archivo, que sera la carpeta /Multimedia/
                String Dest= "/resources/"+archivo.getName();
                Path Destino= Paths.get(Dest);
                //Definimos el origen, que sera el archivo seleccionado
                String Orig= archivo.getPath();
                Path Origen= Paths.get(Orig);
                ///Copiamos el nuevo archivo con la clase Files, reemplazamos si ya existe uno igual
                //Files.copy(Origen,Destino,REPLACE_EXISTING);//Mover de sitio
                
                if (new EvaluaExtension().accept(archivo, ".jpeg")||new EvaluaExtension().accept(archivo, ".jpg")||new EvaluaExtension().accept(archivo, ".png")) {
                    this.urlPerfil = Dest;
                    System.out.println(urlPerfil);
                }else{
                    this.fa.muestraExcepcion("La extensión seleccionada es incorrecta");
                }
                
                try{
                    Image img = ImageIO.read(getClass().getResource(this.urlPerfil));
                    this.fotoPerfil1.setIcon(new javax.swing.ImageIcon(img));
                }catch(Exception ex){
                    System.out.println(ex.getMessage());
                }
              
            } catch (Exception ex) {
                Logger.getLogger(VGallery.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnSubir1ActionPerformed

    private void fotoPerfil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoPerfil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fotoPerfil1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox btnGenero;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterEmpresa;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JRadioButton btnSoltero;
    private javax.swing.JButton btnSubir;
    private javax.swing.JButton btnSubir1;
    private javax.swing.JFileChooser exploradorArchivos;
    private javax.swing.JToggleButton fotoPerfil;
    private javax.swing.JToggleButton fotoPerfil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblConfirmarClave;
    private javax.swing.JLabel lblConfirmarClave1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblFalloEmail;
    private javax.swing.JLabel lblFalloEmailEmpresa;
    private javax.swing.JLabel lblFalloFecha;
    private javax.swing.JLabel lblFalloId;
    private javax.swing.JLabel lblFalloIdEmpresa;
    private javax.swing.JLabel lblFalloPassword;
    private javax.swing.JLabel lblFalloPasswordEmpresa;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblFoto1;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblNickname1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblWeb;
    private javax.swing.JTextField txtBiografia;
    private javax.swing.JTextField txtBiografiaEmpresa;
    private javax.swing.JTextField txtCif;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtConfirmPasswordEmpresa;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailEmpresa;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdEmpresa;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordEmpresa;
    private javax.swing.JTextField txtWeb;
    // End of variables declaration//GEN-END:variables
}

class EvaluaExtension implements FilenameFilter {
 
    @Override
    public boolean accept(File dir, String extension) {
        return dir.getName().endsWith(extension);
    }
}
