/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JSlider;
import javax.swing.KeyStroke;
import app.Party;
import app.Location;

/**
 *
 * @author alumnogreibd
 */
public class VSearchParty extends javax.swing.JDialog {

    private static final String COMMIT_ACTION = "commit";
    private app.FachadaAplicacion fa;
    //private PopupMenu popFestas;
    /**
     * Creates new form VBuscarFesta
     */
    public VSearchParty(java.awt.Frame parent, boolean modal, app.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        BackgroundPanel panelFondo = new BackgroundPanel("/resources/background.png");
        setContentPane(panelFondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.checkHabilitarUbicacion.setEnabled(false);
        this.checkPrivada.setEnabled(false);
        this.checkPublica.setEnabled(false);
        this.btnBuscarUbicacion.setEnabled(false);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                ((VPrincipal)getParent()).actualizarLblSaldo();
            }
        });
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labNomeFesta = new javax.swing.JLabel();
        txtNomeFesta = new javax.swing.JTextField();
        labOrganizador = new javax.swing.JLabel();
        txtOrganizador = new javax.swing.JTextField();
        labTematica = new javax.swing.JLabel();
        txtTematica = new javax.swing.JTextField();
        labPrivacidade = new javax.swing.JLabel();
        comboPrivacidade = new javax.swing.JComboBox();
        labFecha = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        btnBuscarFesta = new javax.swing.JButton();
        panelUbicacions = new javax.swing.JScrollPane();
        listaUbicacions = new javax.swing.JList();
        labUbicacions = new javax.swing.JLabel();
        checkPublica = new javax.swing.JCheckBox();
        checkPrivada = new javax.swing.JCheckBox();
        txtNomeUbicacion = new javax.swing.JTextField();
        labNomeUbicacion = new javax.swing.JLabel();
        btnBuscarUbicacion = new javax.swing.JButton();
        panelFestas = new javax.swing.JScrollPane();
        listaFestas = new javax.swing.JList();
        labFestas = new javax.swing.JLabel();
        slideRadio = new javax.swing.JSlider();
        labRadio = new javax.swing.JLabel();
        checkHabilitarUbicacion = new javax.swing.JCheckBox();
        labValorSlider = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Festas");

        labNomeFesta.setText("Nome");

        txtNomeFesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFestaActionPerformed(evt);
            }
        });

        labOrganizador.setText("Organizador");

        labTematica.setText("Temática");

        txtTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTematicaActionPerformed(evt);
            }
        });

        labPrivacidade.setText("Privacidade");

        comboPrivacidade.setBackground(new java.awt.Color(250, 240, 250));
        comboPrivacidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Privada", "Publica" }));
        comboPrivacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPrivacidadeActionPerformed(evt);
            }
        });

        labFecha.setText("Fecha");

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        btnBuscarFesta.setBackground(new java.awt.Color(250, 240, 250));
        btnBuscarFesta.setText("Buscar");
        btnBuscarFesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFestaActionPerformed(evt);
            }
        });

        panelUbicacions.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listaUbicacions.setBackground(new java.awt.Color(255, 245, 255));
        listaUbicacions.setModel(new gui.TagsListModel());
        listaUbicacions.setCellRenderer(new ImageListCellRenderer());
        panelUbicacions.setViewportView(listaUbicacions);

        labUbicacions.setText("Ubicacions");

        checkPublica.setText("Publicas");
        checkPublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPublicaActionPerformed(evt);
            }
        });

        checkPrivada.setText("Privadas");

        txtNomeUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUbicacionActionPerformed(evt);
            }
        });

        labNomeUbicacion.setText("Nome");

        btnBuscarUbicacion.setBackground(new java.awt.Color(250, 240, 250));
        btnBuscarUbicacion.setText("buscar");
        btnBuscarUbicacion.setMaximumSize(new java.awt.Dimension(18, 18));
        btnBuscarUbicacion.setMinimumSize(new java.awt.Dimension(18, 18));
        btnBuscarUbicacion.setPreferredSize(new java.awt.Dimension(18, 18));
        btnBuscarUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUbicacionActionPerformed(evt);
            }
        });

        panelFestas.setBackground(new java.awt.Color(255, 245, 255));
        panelFestas.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listaFestas.setModel(new gui.TagsListModel());
        listaFestas.setCellRenderer(new ImageListCellRenderer());
        listaFestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFestasMouseClicked(evt);
            }
        });
        panelFestas.setViewportView(listaFestas);

        labFestas.setText("Festas:");

        slideRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slideRadioStateChanged(evt);
            }
        });

        labRadio.setText("Radio");

        checkHabilitarUbicacion.setText("Habilitar");
        checkHabilitarUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHabilitarUbicacionActionPerformed(evt);
            }
        });

        labValorSlider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labValorSlider.setText("50");

        jLabel1.setText("Powered by Altavista ©");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labNomeFesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeFesta, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(labOrganizador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrganizador))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labTematica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTematica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labPrivacidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboPrivacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(slideRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labValorSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarFesta))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labNomeUbicacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeUbicacion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkPublica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkPrivada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscarUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelUbicacions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labUbicacions)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkHabilitarUbicacion)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labFestas)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(panelFestas)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNomeFesta)
                    .addComponent(txtNomeFesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labOrganizador)
                    .addComponent(txtOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTematica)
                    .addComponent(txtTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labPrivacidade)
                    .addComponent(comboPrivacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labRadio))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarFesta)
                        .addComponent(labValorSlider))
                    .addComponent(slideRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUbicacions)
                    .addComponent(labFestas)
                    .addComponent(checkHabilitarUbicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labNomeUbicacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarUbicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkPrivada, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(checkPublica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelUbicacions, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelFestas, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFestaActionPerformed

    private void btnBuscarFestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFestaActionPerformed
        // TODO add your handling code here:
        buscarFestas();
    }//GEN-LAST:event_btnBuscarFestaActionPerformed

    private void buscarFestas()
    {
        TagsListModel me;
        me = (TagsListModel) listaFestas.getModel();
        
        TagsListModel mu;
        mu = (TagsListModel) listaUbicacions.getModel();
        
        java.util.List<ContainerTag> etiquetas = new java.util.ArrayList<>();
        
        java.util.List<Party> festas = new java.util.ArrayList<>();
        
        try
        {
            
            Date data = null;
            
            if(!txtData.getText().isEmpty())
            {
                data = new SimpleDateFormat("dd/MM/yyyy").parse(txtData.getText());
            }  

            if(checkHabilitarUbicacion.isSelected())
            {
                if(mu.getSize() > 0)
                {
                    if(listaUbicacions.getSelectedIndex() != -1)
                    {
                        Container<Location> contenedor = mu.getElementAt(listaUbicacions.getSelectedIndex()).getContenedor();
                        Location ubicacion = contenedor.getContido();
                        //festas = fa.buscarFestasUbicacion(txtNomeFesta.getText(), txtOrganizador.getText(), txtTematica.getText().isEmpty() ? null : txtTematica.getText().toLowerCase(),
                                //(String)comboPrivacidade.getSelectedItem(), data, ubicacion, (float)slideRadio.getValue());
                    }
                }
            }
            else
            {
                festas = this.fa.buscarFestas(this.fa.getUsuarioActual().getId(),txtNomeFesta.getText(), txtOrganizador.getText(), txtTematica.getText().isEmpty() ? null : txtTematica.getText().toLowerCase(), (String)comboPrivacidade.getSelectedItem(), (java.sql.Date) data);
            }

            for(Party festa : festas)
            {
                Container<Party> contenedor = new Container<>(festa);
                etiquetas.add(new ContainerTag(contenedor));
            }
            me.setElementos(etiquetas);
        }
        catch(ParseException pe)
        {
            fa.muestraExcepcion("Introduce unha fecha no formato: dd/MM/yyyy");
        }
    }
    
    private void checkPublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPublicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPublicaActionPerformed

    private void checkHabilitarUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHabilitarUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkHabilitarUbicacionActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void txtNomeUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUbicacionActionPerformed

    private void slideRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slideRadioStateChanged
        // TODO add your handling code here:
        labValorSlider.setText(Integer.toString(((JSlider)evt.getSource()).getValue()));
    }//GEN-LAST:event_slideRadioStateChanged

    private void btnBuscarUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUbicacionActionPerformed
        // TODO add your handling code here:
        if(checkPrivada.isSelected() || checkPublica.isSelected())
        {
            buscarUbicacions();
        }
    }//GEN-LAST:event_btnBuscarUbicacionActionPerformed

    private void comboPrivacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPrivacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPrivacidadeActionPerformed

    private void listaFestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFestasMouseClicked
       
            this.abrirVentanaFesta();
        
    }//GEN-LAST:event_listaFestasMouseClicked

    private void txtTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTematicaActionPerformed

    public void abrirVentanaFesta()
    {
        TagsListModel me;
        Boolean organizador=false;
        me = (TagsListModel) listaFestas.getModel();
        
        if(me.getSize() > 0)
        {
            if(listaFestas.getSelectedIndex() != -1)
            {
                Container<Party> contenedor = (me.getElementAt(listaFestas.getSelectedIndex())).getContenedor();
                Party festa = contenedor.getContido();
                if(this.fa.consultarOrganizador(festa.getId()).equals(this.fa.getUsuarioActual().getId())){
                    organizador=true;
                }
                VParty vf=new VParty(this.fa.getFachadaGui().getVPrincipal(), true,this.fa, festa.getId(),this.fa.consultarPosts(festa.getId()),organizador, (String)this.comboPrivacidade.getSelectedItem());
                vf.setVisible(true);
            }
        }
    }
    
   
                
    private void buscarUbicacions()
    {
       /* TagsListModel me;
        me = (TagsListModel) listaUbicacions.getModel();
        
        java.util.List<Ubicacion> ubicacions = fa.buscarUbicacions(txtNomeUbicacion.getText(), checkPublica.isSelected(), checkPrivada.isSelected());

        java.util.List<EtiquetaContenedor> etiquetas = new java.util.ArrayList<>();
        
        for(Location ubicacion : ubicacions)
        {
            Container<Ubicacion> contenedor = new Container<>(ubicacion);
            etiquetas.add(new ContainerTag(contenedor));
        }
        
        me.setElementos(etiquetas);*/
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFesta;
    private javax.swing.JButton btnBuscarUbicacion;
    private javax.swing.JCheckBox checkHabilitarUbicacion;
    private javax.swing.JCheckBox checkPrivada;
    private javax.swing.JCheckBox checkPublica;
    private javax.swing.JComboBox comboPrivacidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labFecha;
    private javax.swing.JLabel labFestas;
    private javax.swing.JLabel labNomeFesta;
    private javax.swing.JLabel labNomeUbicacion;
    private javax.swing.JLabel labOrganizador;
    private javax.swing.JLabel labPrivacidade;
    private javax.swing.JLabel labRadio;
    private javax.swing.JLabel labTematica;
    private javax.swing.JLabel labUbicacions;
    private javax.swing.JLabel labValorSlider;
    private javax.swing.JList listaFestas;
    private javax.swing.JList listaUbicacions;
    private javax.swing.JScrollPane panelFestas;
    private javax.swing.JScrollPane panelUbicacions;
    private javax.swing.JSlider slideRadio;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtNomeFesta;
    private javax.swing.JTextField txtNomeUbicacion;
    private javax.swing.JTextField txtOrganizador;
    private javax.swing.JTextField txtTematica;
    // End of variables declaration//GEN-END:variables
}
